#!/bin/bash

# Script intended to be executed from ncmpcpp (execute_on_song_change
# preference) running from urxvt to set album cover as background image

# Copyright (c) 2013  Vyacheslav Levit
# Licensed under The MIT License: http://opensource.org/licenses/MIT

MUSIC_DIR=$MUSIC/library

#IM_ARGS=(-limit memory 32mb -limit map 64mb)

function reset_background
{
    # is there any better way?
    printf "\e]20;;100x100+1000+1000\a"
}

{
    file="$(mpc --format %file% current)"
    album_dir="${file%/*}"
    [[ -z "$album_dir" ]] && exit 1
    album_dir="$MUSIC_DIR/$album_dir"

    cover=$(find "$album_dir" -regex "$album_dir/cover.[a-z]+$" | head -n1)
    if [[ -f "$cover" ]]; then
        tmp_cover="/tmp/2-$(basename $cover)"
        cp "$cover" "$tmp_cover"
        # resize the image's width to 700px
        # convert "$cover" -resize 700x "$COVER"
    fi
    printf "\e]20;${tmp_cover};55x75+50+50:op=keep-aspect\a"
    if [[ ! -f "$cover" ]]; then
        reset_background
    fi
} &
