#!/usr/bin/env zsh

while getopts ":h" opt; do
    case "$opt" in
        h)
            echo "usage: skak [-h]"
            return 0
            ;;
        \?)
            echo "unknown option: -$OPTARG" >&2
            return 1
            ;;
    esac
done
shift $((OPTIND-1))

local target=$(skag $@ | perl -pe 's/^(.*?):(\d+):\s*.*?$/\1 +\2/')
[[ -z "$target" ]] && return 1
eval $EDITOR $target
